services:
  frontend:
    container_name: anewsfeedclient
    build:
      context: client
      dockerfile: .dockerfile
    ports:
    - "4201:80"
    - "4200:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  backend:
    container_name: gonewsfeedapi
    build:
      context: api
      dockerfile: .dockerfile
    ports:
      - "3000:3000"