services:
  frontend:
    container_name: anewsfeedclient
    build:
      context: client
      dockerfile: .dockerfile
    ports:
    - "4200:80"

  backend:
    container_name: gonewsfeedapi
    build:
      context: api
      dockerfile: .dockerfile
    ports:
      - "3000:3000"